application: ts-zapis
version: 10-python27
runtime: python27
threadsafe: false
api_version: 1

admin_console:
  pages:
  - name: Stats
    url: /_ah/stats/

#builtins:
#- datastore_admin: on
#- appstats: on
#- remote_api: on
#- deferred: on     

env_variables:
  DJANGO_SETTINGS_MODULE: "settings"

libraries:
- name: django
  version: "1.4"

inbound_services:
- mail

handlers:
- url: /static
  static_dir: static

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
  mime_type: image/x-icon


#- url: /_ah/mail/.+
#  script: inmail.py
#  login: admin

#- url: /cron/.*
#  script: main.py
#  login: admin

#- url: /task/.*
#  script: main.py
#  login: admin

- url: /admin/sys/.*
  script: main.app
  login: admin

#- url: /admin/test/.*
#  script: main.py
#  login: admin

- url: /admin/.*
  script: main.app
  login: required

- url: /.*
  script: main.app


